version: "3"

x-service: &service
  environment:
    - SHELL=/bin/bash
  volumes:
    - ${HOME}:/root
  working_dir: /root
  ports:
    - 8888:8888
  
services:
  conda:
    <<: *service
    image: continuumio/anaconda3:2020.11
    volumes:
      - ${HOME}/tmp:/root
    entrypoint:
      - jupyter
      - lab
      - --LabApp.token=
      - --ip=0.0.0.0
      - --no-browser
      - --allow-root
  jupyter:
    <<: *service
    image: jupyter
    build:
      context: ./jupyter
    ports:
      - 8889:8888
    entrypoint:
      - jupyter
      - lab
      - --LabApp.token=
      - --ip=0.0.0.0
      - --no-browser
      - --allow-root
      - --NotebookApp.allow_origin=https://colab.research.google.com
