version: "3"

x-service: &service
  environment:
    - SHELL=/bin/bash
  volumes:
    - ${HOME}:/home/${USER}
    - ${PWD}:/src
  working_dir: /home/${USER}
  
services:
  gh-pages:
    <<: *service
    image: gh-pages
    build:
      context: ./gh-pages
    working_dir: /src/docs
    environment:
      - JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}
    ports:
      - 80:4000
    entrypoint:
      - jekyll
      - serve
      - --host=0.0.0.0
  jupyter:
    <<: *service
    image: jupyter
    build:
      context: ./jupyter
      args:
        JOVYAN: ${USER}
    ports:
      - 8889:8888
    entrypoint:
      - jupyter
      - lab
      - --LabApp.token=
      - --ip=0.0.0.0
      - --no-browser
      - --NotebookApp.allow_origin=https://colab.research.google.com
  conda:
    <<: *service
    image: conda
    build:
      context: ./conda
      args:
        JOVYAN: ${USER}
    ports:
      - 8888:8888
    entrypoint:
      - jupyter
      - lab
      - --LabApp.token=
      - --ip=0.0.0.0
      - --no-browser
  rstudio:
    <<: *service
    image: rstudio
    build:
      context: ./rstudio
      args:
        RSTUDIO: ${USER}
    ports:
      - 8787:8787
    volumes:
      - ${HOME}:/home/${USER}
    entrypoint:
      - /usr/lib/rstudio-server/bin/rserver
      - --server-daemonize=0
