version: "3"

x-service: &service
  environment:
    - SHELL=/bin/bash
  volumes:
    - ${HOME}:/root
    - ${PWD}:/src
  working_dir: /root
  
services:
  conda:
    <<: *service
    image: continuumio/anaconda3:2020.11
    volumes:
      - ${HOME}/tmp:/root
    ports:
      - 8888:8888
    entrypoint:
      - jupyter
      - lab
      - --LabApp.token=
      - --ip=0.0.0.0
      - --no-browser
      - --allow-root
  gh-pages:
    <<: *service
    image: gh-pages
    build:
      context: ./gh-pages
    working_dir: /src/docs
    environment:
      - JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}
    ports:
      - 80:4000
    entrypoint:
      - jekyll
      - serve
      - --host=0.0.0.0
  jupyter:
    <<: *service
    image: jupyter
    build:
      context: ./jupyter
    ports:
      - 8888:8888
    entrypoint:
      - jupyter
      - lab
      - --LabApp.token=
      - --ip=0.0.0.0
      - --no-browser
      - --allow-root
      - --NotebookApp.allow_origin=https://colab.research.google.com
  rstudio:
    <<: *service
    image: rstudio
    build:
      context: ./rstudio
    ports:
      - 8787:8787
    volumes:
      - ${HOME}:/home/rstudio
    entrypoint:
      - /usr/lib/rstudio-server/bin/rserver
      - --server-daemonize=0

## FIXME consistent user management for rstudio and jupyter
